### ISSUE TITLE
Test suite exhibits non-deterministic behaviour

### ISSUE THREAD

**Issue by rayanht** [americanexpress/one-app-cli#107]
# 🐞 Bug Report

## Describe the bug

The tests located under `packages/one-app-runner/__tests__/bin/one-app-runner.spec.js` will randomly fail from time to time without any modification to the repo.

## To Reproduce

1. Clone the repo
2. `npm install`
3. Run `npm test` or `NODE_ENV=production npx jest` multiple times (it takes me about 5 times on average to hit my first failed run)

## Expected behavior

The tests should either fail every single time or pass every single time.

## System information

- OS: macOS Mojave
- Browser: N/A
- Version of one-app-cli: master
- Node version: I was able to repro with all three of v14.x.x v12.x.x and v10.x.x

**Comment by infoxicator** [comment]
fixed unexpected behaviour on one-app-bundler unit tests here https://github.com/americanexpress/one-app-cli/pull/83
