### ISSUE TITLE
Specify a test path runner will open in browser

### ISSUE THREAD

**Issue by jjallwood** [americanexpress/one-app-cli#259]
# 💡 Feature request

## Is your feature request related to a problem? Please describe

The runner pattern helps us to easily develop modules in isolation. However it can be difficult to know the best URL to be able to preview / test a module. Especially if a module has any required props.

This feature would allow you to specify a path and default query params within a modules code i.e package.json. Then use the runner CLI to open the defined path in a browser. It should be able with any OneApp module; to work on demand, or specifically when the `one-app-runner` instance is available to avoid delay in engineering.

## Example

@JAdshead provided the following API example.

```
"one-amex": {
  "runner": {
    "modules": ["."],
    "startPath: "/demo",
    "startPathParams": {
       "campaignId": "12345",
       "theme": "centurion"    
    }
  }
}

"one-amex": {
  "runner": {
    "modules": ["."],
    "startPath: "/"
  }
}
```

**Comment by nellyk** [comment]
hopefully #269  might resolve part of this
