### ISSUE TITLE
Add envinfo to help maintainers know what a user's environment is

### ISSUE THREAD

**Issue by ryhinchey** [americanexpress/one-app-cli#26]
# 💡 Feature request

## Is your feature request related to a problem? Please describe
[envinfo](https://github.com/tabrindle/envinfo) is a solid package that helps open source maintainers better understand what their users' environments are when they're reporting issues.  I think it'd be helpful to integrate this into the cli so users can better report their environments when filing issues

## Example

this would primarily be in the package.json
```json
{
  "scripts": {
      "get-envinfo": "envinfo --flags --we --deem --relevant"
    }
}

## Describe the solution you'd like

Install envinfo and come up with what parts of a user's OS/environment we want (node/npm versions, browsers, etc)

**Comment by JamesSingleton** [comment]
@ryhinchey would something similar to what babel does in their issue template work? They add this in the template.
```markdown

<!--- Tip: Instead of filling out the questions below, you can run `npx envinfo --preset babel` and paste the result below ``` -->
```

So we could add something like `npx envinfo --system --binaries --npmPackages --npmGlobalPackages --markdown`

**Comment by JamesSingleton** [comment]
Got it, since you don't actually install `one-app-cli` locally you couldn't do `one-app info`, it would have to be in every single dependency.
