### ISSUE TITLE
Remove legacy support from one app bundler

### ISSUE THREAD

**Issue by Harrison-Lara** [americanexpress/one-app-cli#378]
# 💡 Feature request

## Is your feature request related to a problem? Please describe

A clear and concise description of what you want and what your use case is.
I would like to remove legacy support from the build in the one app bundler to help reduce unnecessary bundle size and increase performance. 

## Example

Please include a basic code example of the new feature. Skip this section if not applicable.
Our amex modules tend to become a little bloated even with a few techniques to reduce bundle size and the support from one app provides. Across a few internal teams, there has been a lot of support to remove the legacy support. 

## Describe the solution you'd like

Remove the legacy build from webpack configuration so we only generate the modern build. This will ideally help modules performance and bundle size. 

## Describe alternatives you've considered

One App built in bundle support, dedupe, import techniques, tree shaking, modular imports, etc

## Additional context

Add any other context or screenshots about the feature request here.💡

**Comment by JAdshead** [comment]
currently three different bundles for modules are created, node, browser and legacy-browser. removing support for creating a legacy browser build will only impact old browsers which require that build. Modern browsers do not receive the legacy bundle so this does not impact them

**Comment by JAdshead** [comment]
feel free to open another issue if I have mistaken the intent 🤙
