### ISSUE TITLE
Holocron Dev Server doesn't provide locale files under Windows

### ISSUE THREAD

**Issue by johnlister** [americanexpress/one-app-cli#436]
# 🐞 Bug Report

## Describe the bug

The locale files are not correctly stored in the virtual filesystem on windows, when you try to fetch one you get a html (error) page instead.

## To Reproduce

Use the dev server in a windows environment with a modules using locale files

## Expected behavior

JSON locale files should be returned by the server

## System information

Windows, node 16

## Additional context

path separator hard coded as a forward slash in language-packs.js

**Comment by 10xLaCroixDrinker** [comment]
closed by #445
