### ISSUE TITLE
Tree shaking does not work in One App module

### ISSUE THREAD

**Issue by cmo21** [americanexpress/one-app-cli#451]
I'm building a React component library that bundles with esbuild. My bundle is tree shakable in a create-react-app, but it is not tree shaken when imported into a One App module. I checked the browser build files and see unused components included in the bundle. 

I discussed the issue with Michael Rochester, and he suggested I raise an issue to document this.

**Comment by JAdshead** [comment]
can you confirm that this is happening on a production build ?
