### ISSUE TITLE
one-app-bundler: eslint-loader is deprecated in favor of eslint-webpack-plugin

### ISSUE THREAD

**Issue by aorinevo** [americanexpress/one-app-cli#579]
# 💡 Feature request

Deprecate eslint-loader in favor of eslint-webpack-plugin.

A clear and concise description of what you want and what your use case is.

## Example

Please include a basic code example of the new feature. Skip this section if not applicable.

My team is undertaking dependency management and as part of that, we are attempting to upgrade to latest eslint.  In that process we came to identify that one-app-bundler relies on eslint-loader 4.0.2 which is incompatible with eslint ^8.  This is blocking our adoption of eslint v8.

Replace eslint-loader package with its successor, eslint-webpack-plugin.

One alternative is to force install eslint-loader at the root of our project, however, while this will allow for successful install it creates other issues in the build process.  Other than that, I do not know of any tractable alternate solutions.

**Comment by JAdshead** [comment]
This is already underway in https://github.com/americanexpress/one-app-cli/pull/568 - https://github.com/americanexpress/one-app-cli/pull/568/files/888f13def5b817014155275b7f36a6ec56bf35ec..aa2c5a5ad7f279996b6ab733f777a43ccba0eb8b

Unfortunately when the migration was previously done it resulted in some unexpected breaking changes and had to be reverted.
