### ISSUE TITLE
one-app-dev-bundler: externals support generates a lot of .esbuild-stats files

### ISSUE THREAD

**Issue by smackfu** [americanexpress/one-app-cli#592]
# 🐞 Bug Report

## Describe the bug

With externals support in the one-app-dev-bundler, two `.esbuild-stats` files are created for every external and dumped in the top-level dir of your project.  Even though they are prefixed with a dot and are hidden, many IDEs show all the hidden files.

## To Reproduce

1. Build a module with `bundle-module --dev` using this config:
```
    "bundler": {
      "requiredExternals": [
        "iguazu",
        "iguazu-holocron",
        "iguazu-rpc",
        "iguazu-rest"
      ]
    },
```

2. These file are generated:
```
.esbuild-stats.browser.json
.esbuild-stats.iguazu-holocron.browser.json
.esbuild-stats.iguazu-holocron.node.json
.esbuild-stats.iguazu-rest.browser.json
.esbuild-stats.iguazu-rest.node.json
.esbuild-stats.iguazu-rpc.browser.json
.esbuild-stats.iguazu-rpc.node.json
.esbuild-stats.iguazu.browser.json
.esbuild-stats.iguazu.node.json
.esbuild-stats.node.json
```

## Expected behavior

Ideally these build related filed would be placed in a hidden/ignored subdirectory.

Earlier versions of the dev bundler only generated two files total which was tolerable.

## System information
```
└─┬ @americanexpress/one-app-bundler@6.21.5
  └── @americanexpress/one-app-dev-bundler@1.5.5
```

**Comment by JAdshead** [comment]
I believe this is the offending line - https://github.com/americanexpress/one-app-cli/blob/main/packages/one-app-dev-bundler/esbuild/plugins/time-build.js#L35-L37
